name: FlyPerms
version: ${project.version}
api-version: 1.16
main: dev.benergy10.flyperms.FlyPerms
author: benwoo1110
description: Toggle ability to fly based on permissions!
softdepend: [WorldGuard, PlaceholderAPI, LuckPerms]
commands:
  flyperms:
    description: Base FlyPerms command.
    aliases: [fp, fperms, flypermissions]
permissions:
  flyperms.allow:
    default: false
    description: Give players ability to fly!
  flyperms.speed:
    default: false
    description: Ability to change fly speed.
  flyperms.speed.others:
    default: false
    description: Ability to change fly speed.
  flyperms.info:
    default: false
    description: View info information about this plugin.
  flyperms.listgroups:
    default: false
    description: Show all the speed groups available.
  flyperms.reload:
    default: false
    description: Reload the plugin's config.
  flyperms.help:
    default: false
    description: Reload the plugin's config.
  flyperms.seeallowed:
    default: false
    description: View the condition when you are allowed to fly.
  flyperms.seeallowed.others:
    default: false
    description: View the condition when other players are allowed to fly.
  flyperms.admin:
    default: op
    description: Give Admins access to all FlyPerms commands.
    children:
      - flyperms.speed
      - flyperms.speed.others
      - flyperms.info
      - flyperms.listgroups
      - flyperms.reload
      - flyperms.help
      - flyperms.seeallowed
      - flyperms.seeallowed.others
